// The Spawn State Extension Protocol
//
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: eigr/functions/protocol/actors/state.proto

package actors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A revision is just a version number for a record in the snapshot table that stores the actors' state.
// When an actor has its snaphost timeout, it increments its internal revision number and saves it along with its internal data.
// Some of the persistence adapters can use this revision number to find the state of an Actor at a given point in time.
// As Actors in Spawn persist their internal data as snapshots from time to time a revision number may not indicate the state of a given change
// but will most likely point to the exact time that a given actor's internal state was persisted into the database.
type Revision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_eigr_functions_protocol_actors_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_eigr_functions_protocol_actors_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_eigr_functions_protocol_actors_state_proto_rawDescGZIP(), []int{0}
}

func (x *Revision) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// A checkpoint encapsulates a revision and the state it represents.
type Checkpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revision *Revision   `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	State    *ActorState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_eigr_functions_protocol_actors_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_eigr_functions_protocol_actors_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_eigr_functions_protocol_actors_state_proto_rawDescGZIP(), []int{1}
}

func (x *Checkpoint) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

func (x *Checkpoint) GetState() *ActorState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_eigr_functions_protocol_actors_state_proto protoreflect.FileDescriptor

var file_eigr_functions_protocol_actors_state_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x65, 0x69, 0x67, 0x72, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x65, 0x69,
	0x67, 0x72, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x2a, 0x65, 0x69, 0x67,
	0x72, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x65, 0x69, 0x67,
	0x72, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x65,
	0x69, 0x67, 0x72, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x48, 0x0a, 0x20, 0x69, 0x6f, 0x2e, 0x65, 0x69, 0x67, 0x72, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5a, 0x24, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x2f, 0x65, 0x69, 0x67, 0x72, 0x2f,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_eigr_functions_protocol_actors_state_proto_rawDescOnce sync.Once
	file_eigr_functions_protocol_actors_state_proto_rawDescData = file_eigr_functions_protocol_actors_state_proto_rawDesc
)

func file_eigr_functions_protocol_actors_state_proto_rawDescGZIP() []byte {
	file_eigr_functions_protocol_actors_state_proto_rawDescOnce.Do(func() {
		file_eigr_functions_protocol_actors_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_eigr_functions_protocol_actors_state_proto_rawDescData)
	})
	return file_eigr_functions_protocol_actors_state_proto_rawDescData
}

var file_eigr_functions_protocol_actors_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eigr_functions_protocol_actors_state_proto_goTypes = []any{
	(*Revision)(nil),   // 0: eigr.functions.protocol.state.Revision
	(*Checkpoint)(nil), // 1: eigr.functions.protocol.state.Checkpoint
	(*ActorState)(nil), // 2: eigr.functions.protocol.actors.ActorState
}
var file_eigr_functions_protocol_actors_state_proto_depIdxs = []int32{
	0, // 0: eigr.functions.protocol.state.Checkpoint.revision:type_name -> eigr.functions.protocol.state.Revision
	2, // 1: eigr.functions.protocol.state.Checkpoint.state:type_name -> eigr.functions.protocol.actors.ActorState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_eigr_functions_protocol_actors_state_proto_init() }
func file_eigr_functions_protocol_actors_state_proto_init() {
	if File_eigr_functions_protocol_actors_state_proto != nil {
		return
	}
	file_eigr_functions_protocol_actors_actor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eigr_functions_protocol_actors_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eigr_functions_protocol_actors_state_proto_goTypes,
		DependencyIndexes: file_eigr_functions_protocol_actors_state_proto_depIdxs,
		MessageInfos:      file_eigr_functions_protocol_actors_state_proto_msgTypes,
	}.Build()
	File_eigr_functions_protocol_actors_state_proto = out.File
	file_eigr_functions_protocol_actors_state_proto_rawDesc = nil
	file_eigr_functions_protocol_actors_state_proto_goTypes = nil
	file_eigr_functions_protocol_actors_state_proto_depIdxs = nil
}
