// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: user_example.proto

package actors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeUserNameResponse_Status int32

const (
	ChangeUserNameResponse_OK    ChangeUserNameResponse_Status = 0
	ChangeUserNameResponse_ERROR ChangeUserNameResponse_Status = 1
)

// Enum value maps for ChangeUserNameResponse_Status.
var (
	ChangeUserNameResponse_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	ChangeUserNameResponse_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x ChangeUserNameResponse_Status) Enum() *ChangeUserNameResponse_Status {
	p := new(ChangeUserNameResponse_Status)
	*p = x
	return p
}

func (x ChangeUserNameResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeUserNameResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_user_example_proto_enumTypes[0].Descriptor()
}

func (ChangeUserNameResponse_Status) Type() protoreflect.EnumType {
	return &file_user_example_proto_enumTypes[0]
}

func (x ChangeUserNameResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeUserNameResponse_Status.Descriptor instead.
func (ChangeUserNameResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_user_example_proto_rawDescGZIP(), []int{2, 0}
}

type UserState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserState) Reset() {
	*x = UserState{}
	mi := &file_user_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserState) ProtoMessage() {}

func (x *UserState) ProtoReflect() protoreflect.Message {
	mi := &file_user_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserState.ProtoReflect.Descriptor instead.
func (*UserState) Descriptor() ([]byte, []int) {
	return file_user_example_proto_rawDescGZIP(), []int{0}
}

func (x *UserState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeUserNamePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewName string `protobuf:"bytes,1,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *ChangeUserNamePayload) Reset() {
	*x = ChangeUserNamePayload{}
	mi := &file_user_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNamePayload) ProtoMessage() {}

func (x *ChangeUserNamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNamePayload.ProtoReflect.Descriptor instead.
func (*ChangeUserNamePayload) Descriptor() ([]byte, []int) {
	return file_user_example_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeUserNamePayload) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ChangeUserNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ChangeUserNameResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=examples.actors.ChangeUserNameResponse_Status" json:"status,omitempty"`
}

func (x *ChangeUserNameResponse) Reset() {
	*x = ChangeUserNameResponse{}
	mi := &file_user_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserNameResponse) ProtoMessage() {}

func (x *ChangeUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserNameResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserNameResponse) Descriptor() ([]byte, []int) {
	return file_user_example_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeUserNameResponse) GetStatus() ChangeUserNameResponse_Status {
	if x != nil {
		return x.Status
	}
	return ChangeUserNameResponse_OK
}

var File_user_example_proto protoreflect.FileDescriptor

var file_user_example_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x1f, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x16, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1b, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x70, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x63, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x1a, 0x27, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x69, 0x67, 0x72, 0x2f, 0x73,
	0x70, 0x61, 0x77, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x3b, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_example_proto_rawDescOnce sync.Once
	file_user_example_proto_rawDescData = file_user_example_proto_rawDesc
)

func file_user_example_proto_rawDescGZIP() []byte {
	file_user_example_proto_rawDescOnce.Do(func() {
		file_user_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_example_proto_rawDescData)
	})
	return file_user_example_proto_rawDescData
}

var file_user_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_example_proto_goTypes = []any{
	(ChangeUserNameResponse_Status)(0), // 0: examples.actors.ChangeUserNameResponse.Status
	(*UserState)(nil),                  // 1: examples.actors.UserState
	(*ChangeUserNamePayload)(nil),      // 2: examples.actors.ChangeUserNamePayload
	(*ChangeUserNameResponse)(nil),     // 3: examples.actors.ChangeUserNameResponse
}
var file_user_example_proto_depIdxs = []int32{
	0, // 0: examples.actors.ChangeUserNameResponse.status:type_name -> examples.actors.ChangeUserNameResponse.Status
	2, // 1: examples.actors.UserActor.ChangeUserName:input_type -> examples.actors.ChangeUserNamePayload
	3, // 2: examples.actors.UserActor.ChangeUserName:output_type -> examples.actors.ChangeUserNameResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_example_proto_init() }
func file_user_example_proto_init() {
	if File_user_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_example_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_example_proto_goTypes,
		DependencyIndexes: file_user_example_proto_depIdxs,
		EnumInfos:         file_user_example_proto_enumTypes,
		MessageInfos:      file_user_example_proto_msgTypes,
	}.Build()
	File_user_example_proto = out.File
	file_user_example_proto_rawDesc = nil
	file_user_example_proto_goTypes = nil
	file_user_example_proto_depIdxs = nil
}
